@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/entries

###

POST {{baseUrl}}/entries
Content-Type: application/json

{
  "text": "Another text",
  "author": "John"
}

###

DELETE {{baseUrl}}/entries
Content-Type: application/json

{
  "_id": "62385ec7d3e206db136f9b67"
}
